config/routes.rb
Rails.application.routes.draw do

  get 'chatarea/index'

  get 'chatrooms/index'

  get 'explore/:campus' , to: 'confessions#explore' ,as: :explore
  get 'clubs/:id/photos' , to: "clubs#photos" , as: :clubphotos
  get 'tags/:tag' , to: 'confessions#tags' , as: :tags
devise_for :amitians, controllers: { sessions: 'amitians/sessions' }, path: '',path_names: { sign_in: 'login', sign_out: 'logout'}

root 'home#index'
  resources :amitians  do
    member do
   get :following, :followers
   get :hotlisting
    end
end

get 'amitians/:id/photos' , to: 'amitians#photos' , as: :photos

resources :clubs
resources :clubposts do
 resources :clubscomments
    member do
      get 'like' , to: 'clubposts#upvote'
      get 'dislike' , to: 'clubposts#downvote'
    end
end
resources :clubmembers, only: [:create, :update, :destroy]
resources :events do
 member do
    get :follow
    get :unfollow
  end
end
resources :eventposts do 
  resources :eventcomments
  member do
      get 'like' , to: 'eventposts#upvote'
      get 'dislike' , to: 'eventposts#downvote'
  end
  end
resources :about_amitians, only: [:show,:new,:create,:update,:edit]
resources :friendships, only: [:create, :update, :destroy]
resources :galleries 
resources :chatrooms do
    resources :messages
  end
  resources :confessions do
     resources :confessioncomments   
  	member do
  		get 'like' , to: 'confessions#upvote'
  		get 'dislike' , to: 'confessions#downvote'
  	end
  end

  resources :hotlists

resources :conversations , only: [:create ]  do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  

resources :feeling , only: [:index]
resources :relationships, only: [:create, :destroy]
resources :feedbacks
get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
get 'notifications', to: 'notifications#index' 
post 'notifications' , to: 'notifications#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conversation.rb
class Conversation < ApplicationRecord
	has_many :messages, dependent: :destroy
	belongs_to :sender, foreign_key: :sender_id, class_name: "Amitian"
	belongs_to :recipient, foreign_key: :recipient_id, class_name: "Amitian"

	validates :sender_id, uniqueness: { scope: :recipient_id }

 	scope :between, -> (sender_id, recipient_id) do 
 		where(sender_id: sender_id,
 		recipient_id: recipient_id).or(where(sender_id: recipient_id,
 			recipient_id: sender_id))
 	end

 	def self.get(sender_id,recipient_id)
 			conversation = between(sender_id,recipient_id).first
 			return conversation if conversation.present?

 			create(sender_id: sender_id, recipient_id: recipient_id)

 	end
 	
	def opposed_amitian(amitian)
		amitian == recipient ? sender : recipient
	end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
before_action :authenticate_amitian!

def create 
@conversation = Conversation.get(current_amitian.id, params[:amitian_id])

add_to_conversations unless conversated?

respond_to do |format|
	format.js
end

end

def close
@conversation = Conversation.find(params[:id])
session[:conversations].delete(@conversation.id)
 
    respond_to do |format|
      format.js
    end
end

private

def add_to_conversations
	session[:conversations] ||= []
    session[:conversations] << @conversation.id
end

def conversated?
	session[:conversations].include?(@conversation.id)
end


end

app/views/conversations/_conversation.html.haml
%li
	.panel.panel-default{'data-conversation-id': c.id }
		.panel-heading
			=link_to c.opposed_amitian(amitian).fullname ,'',class: 'toggle-window'
			=link_to 'x' , close_conversation_path(c) , class: 'btn btn-default btn-xs pull-right' , remote: true , method: :post
		.panel-body{'style':{'display':'none;'}}
			.messages-list
				%ul
					=render 'conversations/conversation_content' , messages: c.messages , amitian: amitian


			%form.new_message
				%input{'name':'conversation_id','type':'hidden','value': "#{c.id}"}
				%input{'name':'amitian_id','type':'hidden' , 'value':"#{amitian.id}"}
				%textarea{'name':'body','class':'form-control'}
				%input{'type':'submit','class':'btn btn-success' , 'value':'send'}
			

app/views/conversations/_conversation_content.html.haml
-messages.each do |message|
	= render 'messages/message' , amitian: amitian , message: message

app/views/conversations/close.js.erb
$('#conversations_list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']").parent().remove();

app/views/conversations/create.js.erb
var conversations = $('#conversations_list');
var conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");

if (conversation.length !== 1) {
  conversations.append("<%= j(render 'conversations/conversation', c: @conversation, amitian: current_amitian) %>");
  conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
}

conversation.find('.panel-body').show();

var messages_list = conversation.find('.messages-list');
var height = messages_list[0].scrollHeight;
messages_list.scrollTop(height);