config/routes.rb
Rails.application.routes.draw do

  get 'chatarea/index'

  get 'chatrooms/index'

  get 'explore/:campus' , to: 'confessions#explore' ,as: :explore
  get 'clubs/:id/photos' , to: "clubs#photos" , as: :clubphotos
  get 'tags/:tag' , to: 'confessions#tags' , as: :tags
devise_for :amitians, controllers: { sessions: 'amitians/sessions' }, path: '',path_names: { sign_in: 'login', sign_out: 'logout'}

root 'home#index'
  resources :amitians  do
    member do
   get :following, :followers
   get :hotlisting
    end
end

get 'amitians/:id/photos' , to: 'amitians#photos' , as: :photos

resources :clubs
resources :clubposts do
 resources :clubscomments
    member do
      get 'like' , to: 'clubposts#upvote'
      get 'dislike' , to: 'clubposts#downvote'
    end
end
resources :clubmembers, only: [:create, :update, :destroy]
resources :events do
 member do
    get :follow
    get :unfollow
  end
end
resources :eventposts do 
  resources :eventcomments
  member do
      get 'like' , to: 'eventposts#upvote'
      get 'dislike' , to: 'eventposts#downvote'
  end
  end
resources :about_amitians, only: [:show,:new,:create,:update,:edit]
resources :friendships, only: [:create, :update, :destroy]
resources :galleries 
resources :chatrooms do
    resources :messages
  end
  resources :confessions do
     resources :confessioncomments   
  	member do
  		get 'like' , to: 'confessions#upvote'
  		get 'dislike' , to: 'confessions#downvote'
  	end
  end

  resources :hotlists

resources :conversations , only: [:create ]  do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  

resources :feeling , only: [:index]
resources :relationships, only: [:create, :destroy]
resources :feedbacks
get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
get 'notifications', to: 'notifications#index' 
post 'notifications' , to: 'notifications#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :amitian
  belongs_to :notified_by, class_name: 'Amitian'
  belongs_to :confession
  belongs_to :club
 
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

before_action :authenticate_amitian!

def index
	@notifications = current_amitian.notifications.paginate(page: params[:page], per_page: 30).order('created_at DESC')
	 @amitian = Amitian.all
   
	 @topstory = TOP_STORY
     @interest = current_amitian.about_amitian.interest if current_amitian.about_amitian.interest?
      male = Amitian.where.not(id: current_amitian.id).order('RAND()').limit(5)
      @male = male.where('gender = "Male"')
      female = Amitian.where.not(id: current_amitian.id).order('RAND()').limit(5)
      @female = female.where('gender = "Female"')
     @friends = current_amitian.active_friends + current_amitian.received_friends

owner = current_amitian.clubs
    member = current_amitian.clubmembers
    @myclubs = owner + member

end

def create
Notification.create(notice_type: params[:notice_type], notified_by_id: params[:notified_by_id] , club_id: params[:club_id] , amitian_id: params[:amitian_id])
render nothing: true
end

def link_through  
  @notification = Notification.find(params[:id])
  @notification.update read: true
  if @notification.notice_type == 'follow' 
  		redirect_to @notification.notified_by
    elsif @notification.notice_type == 'ask_invite'
      redirect_to @notification.club 
	else
	  redirect_to confession_path @notification.confession
	end
end  

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.haml
%li.notif_lnk

	-if notification.notice_type != 'invites'
		-if !notification.notified_by.profilepic? 
			- if notification.notified_by.gender == 'Male'
				=image_tag '93.svg',class:'pic shadow'
			-else
				=image_tag 'manager_photo.svg' , class:'pic shadow'
		-else
			=image_tag((notification.notified_by.profilepic),class:'pic shadow')
	- if notification.notice_type  == 'like'
		= link_to "#{notification.notified_by.fullname} has #{notification.notice_type}d your confession '#{notification.confession.confession[0..30]}'", link_through_path(notification) 
	-elsif notification.notice_type == 'dislike'
		= link_to "#{notification.notified_by.fullname} has #{notification.notice_type}d your confession '#{notification.confession.confession[0..30]}'", link_through_path(notification) 
	-elsif notification.notice_type == 'comment'
		= link_to "#{notification.notified_by.fullname} has #{notification.notice_type}ed on your confession '#{notification.confession.confession[0..30]}'", link_through_path(notification) 
	-elsif notification.notice_type == 'follow'
		= link_to "#{notification.notified_by.fullname} has started #{notification.notice_type}ing you", link_through_path(notification) 
	-elsif notification.notice_type == "ask_invite"
		=link_to "#{notification.notified_by.fullname} has asked to join your club #{notification.club.clubname}", link_through_path(notification) 
		
	-elsif notification.notice_type == 'invites'
		.REQUEST_DIV 
			=image_tag notification.club.club_themepic , class:'pic shadow'
			= link_to 'You are invited to '+notification.club.clubname+' by '+notification.club.amitian.fullname , notification.club
			.text-center
				= link_to "Accept",  clubmember_path(id: notification.club.id,notif_id: notification.id), method: "put" , 'id': "accreq" , class: 'btn btn-default'
				= link_to "Reject", clubmember_path(id: notification.club.id,notif_id: notification.id), method: :delete, 'id':'delreq' , class: 'btn btn-warning'
	




	

app/views/notifications/_notification_dropdown.html.haml

=render  partial: "notifications/notification", collection: current_amitian.notifications.where(read: false).order('created_at DESC').limit(7)	
.REQUEST_DIV
	-if current_amitian.notifications.where(read: false).count == 0 
		.alert.alert-info
			You don't have any notifications

app/views/notifications/index.html.haml
#index_main_div
	.container-fluid
		.row
			.col-sm-6.col-xs-12
				%h1.text-center{'style':'font-weight: 700;'}
					You have
					=pluralize(@notifications.count,'Notification')
				%hr
				%ul
					#notification
						= render @notifications
			.col-sm-3
			= render 'confessions/index_right_confession_div'
#infinitescrolling.text-center
	=will_paginate	@notifications

app/views/notifications/index.js.erb
<% if @notifications %>
$('#notification').append("<%= j render @notifications %>");
$('.pagination').replaceWith("<%= j will_paginate @notifications %>");
<% if !@notifications.next_page %>
  $('.pagination').remove();
<% end %>
<% end %>