config/routes.rb
Rails.application.routes.draw do

  get 'chatarea/index'

  get 'chatrooms/index'

  get 'explore/:campus' , to: 'confessions#explore' ,as: :explore
  get 'clubs/:id/photos' , to: "clubs#photos" , as: :clubphotos
  get 'tags/:tag' , to: 'confessions#tags' , as: :tags
devise_for :amitians, controllers: { sessions: 'amitians/sessions' }, path: '',path_names: { sign_in: 'login', sign_out: 'logout'}

root 'home#index'
  resources :amitians  do
    member do
   get :following, :followers
   get :hotlisting
    end
end

get 'amitians/:id/photos' , to: 'amitians#photos' , as: :photos

resources :clubs
resources :clubposts do
 resources :clubscomments
    member do
      get 'like' , to: 'clubposts#upvote'
      get 'dislike' , to: 'clubposts#downvote'
    end
end
resources :clubmembers, only: [:create, :update, :destroy]
resources :events do
 member do
    get :follow
    get :unfollow
  end
end
resources :eventposts do 
  resources :eventcomments
  member do
      get 'like' , to: 'eventposts#upvote'
      get 'dislike' , to: 'eventposts#downvote'
  end
  end
resources :about_amitians, only: [:show,:new,:create,:update,:edit]
resources :friendships, only: [:create, :update, :destroy]
resources :galleries 
resources :chatrooms do
    resources :messages
  end
  resources :confessions do
     resources :confessioncomments   
  	member do
  		get 'like' , to: 'confessions#upvote'
  		get 'dislike' , to: 'confessions#downvote'
  	end
  end

  resources :hotlists

resources :conversations , only: [:create ]  do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  

resources :feeling , only: [:index]
resources :relationships, only: [:create, :destroy]
resources :feedbacks
get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
get 'notifications', to: 'notifications#index' 
post 'notifications' , to: 'notifications#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  		if amitian_signed_in?
  			redirect_to confessions_path
  	  end
  	 end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.haml
#footer.navbar.navbar-default.text-center
	%ul
		%li{'data-target':'#aboutmodal' , 'data-toggle':'modal'}
			%a.modallink About 
		%li{'data-target':'#helpmodal' , 'data-toggle':'modal'}
			%a.modallink Help
		%li{'data-target':'#tncmodal' , 'data-toggle':'modal'}
			%a.modallink Terms and conditions
		%li{'data-target':'#jobmodal' , 'data-toggle':'modal'}
			%a.modallink Get a job
		%li{'data-target':'#adsmodal' , 'data-toggle':'modal'}
			%a.modallink Ads
		%li=link_to 'CEO @AlaapDhall' , 'https://www.alaapdhall.in' , 'target':'_blank'

app/views/home/index.html.haml
#index_main_div_home
	.home_div
		.home_title
	#home_container_div
		#details.white
			#home_start
				#tagline
					%p.h1
						Step Into the Biggest Network of Amity
					%hr.hr1
				#detail1
					%p 
						Amity Humor is a unique platform build with the Idea to connect all the campuses of Amity and their students. Amity Humor is specifically designed to build your profiles and make relations with other students regard or regardless of your branch or campus. Amity Humor provide every amitian a unique platfrom called 
						=link_to 'Feeling Lucky' , feeling_index_path , 'title':'Find a partner'
						which give you a way to find and connect with a partner. Amity Humor allow you to confess your feelings without revealing your identity, if you wish so.

			.container-fluid
				#images.row
					#left.col-md-4.col-sm-4.col-xs-12
						=image_tag('confessionshome.jpg','class':'shadow2')
					#right.col-md-4.col-sm-4.col-xs-12
						=image_tag('tinder.png','class':'shadow2')
					#mid.col-md-4.col-sm-4.col-xs-12
						=image_tag('postsecret.jpg','class':'shadow2')
			%hr
			%hr
			#why.text-center
				%h1
					WHY AMITY HUMOR ?
					%br
					%small cz we know what a college student want
			%hr
			%hr
			.container-fluid
				#detail2.row
					.col-sm-5.col-xs-12.home_anony
						= image_tag 'anonypost.JPG' , class: 'thumbnail'
					
					=image_tag 'tick.png' , class:'tickimage'
					.col-sm-6.col-xs-offset-1.col-xs-12.home_anony_text
						.text-center
							.h1.grey Want to say things, yet mantainnig privacy.
						%p
							%b DONE !!
							Posting your secret was never this easy
						%p
							Why reveal your identity when you can confess Annonymously with amityhumor.com.
							%br
							Next tym when you are frustrated because your attendance is short and need someone to blame but shy enough to not show your identity ?
							Well, 
							Go on post Anonymously so that no one knows its you but you somewhere deep inside your mischief heart.
							Simply select your campus and institute to get 
							%b=link_to 'started' , amitian_session_path
						%p
							So, next time there is this boy who is hot as hell and baby you wanna confess.... welcome to
							@amityhumor.com
							%br
							or who knows Maybe you have a 
							%em pataka 
							senior ?
						Don't stop from confessing because you actuallly don't have to reveal your identity.
						%br
			%hr
			%hr
			.container-fluid
				#details3.row
					.col-sm-5.col-xs-12.home_anony
						= image_tag 'dating.jpg' , class: 'img-thumbnail'
					
					=image_tag 'tick.png' , class: 'tickimage'
					.col-sm-6.col-xs-offset-1.col-xs-12.home_anony_text
						.text-center
							.h1.grey 
								Write your own 
								%s Love
								Hope story.
						%p 
							%b 
								DONE !!
								We care for you, so we listen to you.
								You Need a partner ? We got it for you ...
							Amity Humor is not at all limited to confessions and clubs... it is so much more than that.
						
						%p 
							Using the best match finder algorithms we have build a platform we proudly call
							%b
								= link_to 'Feeling Lucky ?' , feeling_index_path
						With Feeling lucky, you can find your best suited match and add them to 
						%b
							%em
								Hotlist
						to check them later or directly Poke them..
						If they Poke you back...
						%b
							BINGOOO
						Your Send Message option will be unlocked and you are good to go further with your match and convert it into your own hope or my be love ? story.
						%br
						.text-center
							%br
							%b
								%em GOD, We can feel your Excitement, but wait, there is more.


			%hr
			%hr
			.container-fluid
				#details4.row
					.col-sm-5.col-xs-12.home_anony
						= image_tag 'Clubs.png' , class: 'thumbnail'
					
					=image_tag 'tick.png' ,class: 'tickimage'
					.col-sm-6.col-xs-offset-1.col-xs-12.home_anony_text
						.text-center
							.h1.grey 
								Show off your Clubs and Organize your Events
						%p 
							%b
								DONE !!
							We know how hard it can be for you to get some volunteers and give them pamphlets
							to pin on every pin board of your department and announce in classes. Keeping that in Mind we bring you
							%b Clubs
							and
							%b Events
						
							creation capability in Amity Humor. 
							%p
								We understand your problems and try our best to solve them in the best way possible. With AmityHumor you can create your Clubs and orgnize events right away with just
								%b 
									one click
								and you are good to go and invite everyone to join your event and clubs.
							%b
								%em
									Events can be associated either to your club or to you yourself.

			%hr
			%hr
			.container-fluid
				#details3.row
					.col-sm-5.col-xs-12.home_anony
						= image_tag 'campuses.jpg' , class: 'img-thumbnail'

					=image_tag 'tick.png' , class: 'tickimage'
					.col-sm-6.col-xs-offset-1.col-xs-12.home_anony_text
						.text-center
							.h1.grey 
								Travel and Explore outside your campus
						%p 
							%b
								DONE !!
							Our aim is not only to enlighten you with news feed of your campus but to expose you to Every Campus of Amity in only 
							%b 
								one tap
								%em
									that will take you to the tour of any campus you want
							Explroe will bring you to the world of Campuses and let you Explore Everything going around campus. Look for the Top events, confessions, most hated confessions look for latest matches and just so much more. Explore is an ulimited exposure of every campus that you would ever want to see.
							Now what are you waiting for ?
							%b= link_to 'Sign Up' , new_amitian_registration_path
							Now and become our family member. 
			%hr
			%hr
			.container-fluid.text-center
				.h3.lead
					Join Amity Humor Family Now 
				= link_to 'Join Now', new_amitian_registration_path , class:'btn btn-primary'
				%br
				%small
					Already have an account ? 
					=link_to 'Sign in' , amitian_session_path

			%footer.footer
				= render 'home/footer'