config/routes.rb
Rails.application.routes.draw do

  get 'chatarea/index'

  get 'chatrooms/index'

  get 'explore/:campus' , to: 'confessions#explore' ,as: :explore
  get 'clubs/:id/photos' , to: "clubs#photos" , as: :clubphotos
  get 'tags/:tag' , to: 'confessions#tags' , as: :tags
devise_for :amitians, controllers: { sessions: 'amitians/sessions' }, path: '',path_names: { sign_in: 'login', sign_out: 'logout'}

root 'home#index'
  resources :amitians  do
    member do
   get :following, :followers
   get :hotlisting
    end
end

get 'amitians/:id/photos' , to: 'amitians#photos' , as: :photos

resources :clubs
resources :clubposts do
 resources :clubscomments
    member do
      get 'like' , to: 'clubposts#upvote'
      get 'dislike' , to: 'clubposts#downvote'
    end
end
resources :clubmembers, only: [:create, :update, :destroy]
resources :events do
 member do
    get :follow
    get :unfollow
  end
end
resources :eventposts do 
  resources :eventcomments
  member do
      get 'like' , to: 'eventposts#upvote'
      get 'dislike' , to: 'eventposts#downvote'
  end
  end
resources :about_amitians, only: [:show,:new,:create,:update,:edit]
resources :friendships, only: [:create, :update, :destroy]
resources :galleries 
resources :chatrooms do
    resources :messages
  end
  resources :confessions do
     resources :confessioncomments   
  	member do
  		get 'like' , to: 'confessions#upvote'
  		get 'dislike' , to: 'confessions#downvote'
  	end
  end

  resources :hotlists

resources :conversations , only: [:create ]  do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  

resources :feeling , only: [:index]
resources :relationships, only: [:create, :destroy]
resources :feedbacks
get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
get 'notifications', to: 'notifications#index' 
post 'notifications' , to: 'notifications#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/modals/_aboutmodal.html.haml
#aboutmodal.modal.fade.m{'tabindex':-1 , 'role':'dialog','aria-labelledby':'aboutmodal'}
	.modal-dialog.modal-lg{'role':'document'}
		.modal-content
			.modalheader
				%h1.h1.text-center
					Welcome to AmityHumor
					%small.lead
						created_by 
						%signature.signature Alaap Dhall
			%b.lead
				Amity Humor is a platform build with a mission to create a central network for all the Amity Campuses around the world.
				#about_img.shadow2
					=image_tag('am.jpg')
					%p.text-center.lead.imghead
						We're One
				%p
					It's an honor to work on a project like this and unite all the amitians from around the world.
					This is no 
					%em
						Amizone.
				.margin
				#row.row
					#col1.col-md-6.text-center
						.about_details.shadow
							=image_tag('anonydp.jpg')
							%h3
								Anonymous 
							%p
								Go Anonymous this time with Amity Humor.
								So, you don't really have to think twice before you CONFESS YOUR MIND.

					#col2.col-md-6.text-center
						.about_details.shadow
							=image_tag('heart.jpg')
							%h3
								Feeling lucky?
							%p
								We give you a list. You see it, Find your match...Create your own hope story. You are the reason for the people around you.
				.margin
				#row.row
					#col1.col-md-6.text-center
						.about_details.shadow
							=image_tag('Club.ico')
							%h3
								Clubs and Events
							%p
								You don't have to worry about advertising your clubs and events cz we gave you the key platform to create clubs and manage events.
								
					#col2.col-md-6.text-center
						.about_details.shadow
							=image_tag('search.jpg')
							%h3
								Inside Campus
							%p
								If you are done with confessions and need to know what's going on in or outside your campus? Well, we exactly know what you want.
				.margin		
				#row.row
					#col1.col-md-6.text-center
						.about_details.shadow
							=image_tag('follow.jpg')
							%h3
								Follow
							%p
								You only receive newsfeed from people belongs to your department. In order to receive feeds from others you can follow them to enlarge your family.
								
					#col2.col-md-6.text-center
						.about_details.shadow
							=image_tag('gallery.jpg')
							%h3
								Gallery
							%p
								Personify your profile with a 6 image Gallery. Your gallery will have a huge impact on who Pokes you, and can change your hope story for and ever.


								
						

app/views/modals/_ads.html.haml
#adsmodal.modal.fade.m{'tabindex':-1 , 'role':'dialog','aria-labelledby':'aboutmodal'}
	.modal-dialog.modal-lg{'role':'document'}
		.modal-content
			%h1 Amity Confessions is completely Ads Free... :)
			If you have an ad to show on amity confessions or you have an event you want to promote .. contact.

app/views/modals/_club_create.html.haml
#clubs_create.modal.fade.m{'tabindex':-1 , 'role':'dialog','aria-labelledby':'aboutmodal'}
	.modal-dialog.modal-lg{'role':'document'}
		.modal-content
			= render 'clubs/create'

app/views/modals/_create_a_page.html.haml
#create_a_page.modal.fade.m{'tabindex':-1 , 'role':'dialog','aria-labelledby':'aboutmodal'}
	.modal-dialog.modal-lg{'role':'document'}
		.modal-content
			.lead.grey Comming Soon...

app/views/modals/_event_form.html.haml
.lead.grey.text-center
	Create an Event

.form-group.text-center
	=f.label :event_themepic , "Upload Event Theme" , class: 'filebutton'
	%span.fileimage
		=f.file_field :event_themepic
%hr
.form-group
	= f.label :Name , "Event Name  "
	=f.text_field :eventtheme
.form-group
	= f.label :EventTagLine  , "Event Tagline  "
	= f.text_field :tags 
.form-group
	= f.label :Location   , "Location of Event  "
	=f.text_field :location
%hr
.lead.text-center
	Event Timmings
.form-group
	= f.label :StartTime  , "Start  "
	=f.datetime_local_field :start 
.form-group
	= f.label :EndTime  , "End  "
	=f.datetime_local_field :endtime
%hr
.form-group
	= f.label :AboutEvent , "About "
	=f.text_area :description , class: 'form-control'
.form-group
	= f.label :department , "Organizing Department "
	=f.text_field :department
.form-group
	=f.label :niche
	=f.select :niche, options_for_select([['Entertainment','Entertainment'],['Dance','Dance'],['Technical','Technical'],['Music' , 'Music'] ,['Party','Party'],['Fest','Fest'],['Fashion','Fashion'] , ['Drama','Drama'], ['Others','Others']]) ,{'class':'form-control'}
.input-group
	=f.submit "Create Event" , class:'btn btn-primary'



app/views/modals/_events_create.html.haml
#events_create.modal.fade.m{'tabindex':-1 , 'role':'dialog','aria-labelledby':'aboutmodal'}
	.modal-dialog.modal-lg{'role':'document'}
		.modal-content
			= form_for @event do |f|
				- if @event.errors.any? 
					-@event.errors.full_messages.each do |message|
						.alert.alert-info
							%li= message
				= hidden_field_tag :club_id , @club.id
				= hidden_field_tag :campus , current_amitian.campus
				=render 'modals/event_form' , f: f

app/views/modals/_events_create_amitian.html.haml
#events_create_amitian.modal.fade.m{'tabindex':-1 , 'role':'dialog','aria-labelledby':'aboutmodal'}
	.modal-dialog.modal-lg{'role':'document'}
		.modal-content
			= form_for @event do |f|
				- if @event.errors.any? 
					-@event.errors.full_messages.each do |message|
						.alert.alert-info
							%li= message
				= hidden_field_tag :campus , current_amitian.campus
				= hidden_field_tag :club_id , 0
				= render 'modals/event_form' , f: f

app/views/modals/_feedback.html.haml
#feedbackmodal.modal.fade.m{'tabindex':-1 , 'role':'dialog','aria-labelledby':'aboutmodal'}
	.modal-dialog.modal-lg{'role':'document'}
		.modal-content
			%h1 Feedback Form / Bug Reports
			.margin
			.margin
			=form_for @feed do |f|
				.form-group
					=f.label :name
					=f.text_field :name , class: 'form-control disabled' , 'placeholder': "#{current_amitian.fullname}"
				.form-group
					=f.label :subject
					=f.text_field :title , class: 'form-control'
				.form-group
					=f.label :content
					=f.text_area :content , class: 'form-control'
				=f.submit 'Leave Feedback', class: 'btn btn-default'

app/views/modals/_gallery_create_modal.html.haml
#gallery_create_modal.modal.fade.m{'tabindex':-1 , 'role':'dialog','aria-labelledby':'creategallery'}
	.modal-dialog.modal-lg{'role':'document'}
		.modal-content
			= render 'galleries/create'

app/views/modals/_getjob.html.haml
#jobmodal.modal.fade.m{'tabindex':-1 , 'role':'dialog','aria-labelledby':'aboutmodal'}
	.modal-dialog.modal-lg{'role':'document'}
		.modal-content
			%h1 works bitch

app/views/modals/_help.html.haml
#helpmodal.modal.fade.m{'tabindex':-1 , 'role':'dialog','aria-labelledby':'aboutmodal'}
	.modal-dialog.modal-lg{'role':'document'}
		.modal-content
			.text-center
				%h1 How to Use
			%p
				%ol
					%p
						%li We use simple FaceBook type Interface to make AmityConfessions more user friendly and provide better user experience.

					%p
						%li When you first sign Up. Your Home page will have feeds from everyone belongs to your department and all the anonymous posts. There is a possibility that your department don't have much feeds to show which results in Too much Anonymous Feeds in your confessions page.
					%p To fill up yout Feeds you can either follow users from other departments or you can ask your friends from your department to join amityconfessions and start confessing with you.
					%p
						%li You don't really have to reveal your identity when you post something. Hide who you are by selectinh annonymous from the selection box in your status bar. This will simply post your confession using an anonymous account from our database so no one will ever know that you are the culprit.
					%p
						%li We decided to make AmityConfessions a protocol to do what every amitian needs the most... A Tinder like gateway to find your partner.
					On the top right corner in navigation bar you can see a 
					%em 'Feeling lucky ?' 
					option. From their you can see all the girls/boys on amity confessions that might interest you.
					If you like someone you can simply goto their profile and Poke them. 
					%br
					Doing that will send a request to them. If they like you back by accepting your request, just like tinder, you both can now send text messages to each other.

app/views/modals/_tnc.html.haml
#tncmodal.modal.fade.m{'tabindex':-1 , 'role':'dialog','aria-labelledby':'aboutmodal'}
	.modal-dialog.modal-lg{'role':'document'}
		.modal-content
			